/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef A_ANDROID_GEN_CLASS_H
#define A_ANDROID_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class a_Android_gen_class
{
 protected:
  string srcname;

 public:
  a_Android_gen_class()
  {
  }
  
  a_Android_gen_class(const string &_srcname) :
    srcname (_srcname)
  {
  }

  void set_srcname(const string &_srcname)
  {
    srcname = _srcname;
  }

  void generate_a_Android(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "###################### ";
    stream << srcname;
    stream << " ######################";
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_PATH := $(call my-dir)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "include $(CLEAR_VARS)";
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_CFLAGS += -DANDROID_BUILD";
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_CFLAGS += -Wall";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_SRC_FILES += host/main.c";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_C_INCLUDES := $(LOCAL_PATH)/ta/include";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_SHARED_LIBRARIES := libteec";
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_MODULE := ";
    stream << srcname;
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_VENDOR_MODULE := true";
    stream << "\n";
    stream << indent_str;
    stream << "LOCAL_MODULE_TAGS := optional";
    stream << "\n";
    stream << indent_str;
    stream << "include $(BUILD_EXECUTABLE)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "include $(LOCAL_PATH)/ta/Android.mk";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // A_ANDROID_GEN_CLASS_H
