/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef A_CMAKELIST_GEN_CLASS_H
#define A_CMAKELIST_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class a_CMakeList_gen_class
{
 protected:
  string srcname;

 public:
  a_CMakeList_gen_class()
  {
  }
  
  a_CMakeList_gen_class(const string &_srcname) :
    srcname (_srcname)
  {
  }

  void set_srcname(const string &_srcname)
  {
    srcname = _srcname;
  }

  void generate_a_CMakeList(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "project (";
    stream << srcname;
    stream << " C)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "set (SRC host/main.c)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "add_executable (${PROJECT_NAME} ${SRC})";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "target_include_directories(${PROJECT_NAME}";
    stream << "\n";
    stream << indent_str;
    stream << "			   PRIVATE ta/include";
    stream << "\n";
    stream << indent_str;
    stream << "			   PRIVATE include)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "target_link_libraries (${PROJECT_NAME} PRIVATE teec)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "install (TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR})";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // A_CMAKELIST_GEN_CLASS_H
