/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef A_MAKEFILE_GEN_CLASS_H
#define A_MAKEFILE_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class a_Makefile_gen_class
{
 protected:

 public:
  a_Makefile_gen_class()
  {
  }
  

  void generate_a_Makefile(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "export V?=0";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "# If _HOST or _TA specific compilers are not specified, then use CROSS_COMPILE";
    stream << "\n";
    stream << indent_str;
    stream << "HOST_CROSS_COMPILE ?= $(CROSS_COMPILE)";
    stream << "\n";
    stream << indent_str;
    stream << "TA_CROSS_COMPILE ?= $(CROSS_COMPILE)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << ".PHONY: all";
    stream << "\n";
    stream << indent_str;
    stream << "all:";
    stream << "\n";
    stream << indent_str;
    stream << "	$(MAKE) -C host CROSS_COMPILE=\"$(HOST_CROSS_COMPILE)\" --no-builtin-variables";
    stream << "\n";
    stream << indent_str;
    stream << "	$(MAKE) -C ta CROSS_COMPILE=\"$(TA_CROSS_COMPILE)\" LDFLAGS=\"\"";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << ".PHONY: clean";
    stream << "\n";
    stream << indent_str;
    stream << "clean:";
    stream << "\n";
    stream << indent_str;
    stream << "	$(MAKE) -C host clean";
    stream << "\n";
    stream << indent_str;
    stream << "	$(MAKE) -C ta clean";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
  }
};

#endif // A_MAKEFILE_GEN_CLASS_H
