/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef APP_H_GEN_CLASS_H
#define APP_H_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class app_h_gen_class
{
 protected:

 public:
  app_h_gen_class()
  {
  }
  

  void generate_app_h(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "#ifndef _APP_H_";
    stream << "\n";
    stream << indent_str;
    stream << "#define _APP_H_";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "#endif /* !_APP_H_ */";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
  }
};

#endif // APP_H_GEN_CLASS_H
