/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef ENCLAVE_H_GEN_CLASS_H
#define ENCLAVE_H_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class enclave_h_gen_class
{
 protected:

 public:
  enclave_h_gen_class()
  {
  }
  

  void generate_enclave_h(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "#ifndef _ENCLAVE_H_";
    stream << "\n";
    stream << indent_str;
    stream << "#define _ENCLAVE_H_";
    stream << "\n";
    stream << indent_str;
    stream << "#endif";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
  }
};

#endif // ENCLAVE_H_GEN_CLASS_H
