/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef HOST_MAKEFILE_GEN_CLASS_H
#define HOST_MAKEFILE_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class host_Makefile_gen_class
{
 protected:
  string srcname;

 public:
  host_Makefile_gen_class()
  {
  }
  
  host_Makefile_gen_class(const string &_srcname) :
    srcname (_srcname)
  {
  }

  void set_srcname(const string &_srcname)
  {
    srcname = _srcname;
  }

  void generate_host_Makefile(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << " CC      ?= $(CROSS_COMPILE)gcc";
    stream << "\n";
    stream << indent_str;
    stream << " LD      ?= $(CROSS_COMPILE)ld";
    stream << "\n";
    stream << indent_str;
    stream << " AR      ?= $(CROSS_COMPILE)ar";
    stream << "\n";
    stream << indent_str;
    stream << " NM      ?= $(CROSS_COMPILE)nm";
    stream << "\n";
    stream << indent_str;
    stream << " OBJCOPY ?= $(CROSS_COMPILE)objcopy";
    stream << "\n";
    stream << indent_str;
    stream << " OBJDUMP ?= $(CROSS_COMPILE)objdump";
    stream << "\n";
    stream << indent_str;
    stream << " READELF ?= $(CROSS_COMPILE)readelf";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << " OBJS = main.o";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << " CFLAGS += -Wall -I../ta/include -I$(TEEC_EXPORT)/include -I./include";
    stream << "\n";
    stream << indent_str;
    stream << " #Add/link other required libraries here";
    stream << "\n";
    stream << indent_str;
    stream << " LDADD += -lteec -L$(TEEC_EXPORT)/lib";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << " BINARY = ";
    stream << srcname;
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << " .PHONY: all";
    stream << "\n";
    stream << indent_str;
    stream << " all: $(BINARY)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << " $(BINARY): $(OBJS)";
    stream << "\n";
    stream << indent_str;
    stream << "	$(CC) -o $";
    stream << "@";
    stream << " $< $(LDADD)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << " .PHONY: clean";
    stream << "\n";
    stream << indent_str;
    stream << " clean:";
    stream << "\n";
    stream << indent_str;
    stream << "  	rm -f $(OBJS) $(BINARY)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << " %.o: %.c";
    stream << "\n";
    stream << indent_str;
    stream << " 	$(CC) $(CFLAGS) -c $< -o $";
    stream << "@";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
  }
};

#endif // HOST_MAKEFILE_GEN_CLASS_H
