/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TA_ANDROID_GEN_CLASS_H
#define TA_ANDROID_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class ta_Android_gen_class
{
 protected:

 public:
  ta_Android_gen_class()
  {
  }
  

  void generate_ta_Android(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "LOCAL_PATH := $(call my-dir)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "local_module := 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta";
    stream << "\n";
    stream << indent_str;
    stream << "include $(BUILD_OPTEE_MK)";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
  }
};

#endif // TA_ANDROID_GEN_CLASS_H
