/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TA_MAKEFILE_GEN_CLASS_H
#define TA_MAKEFILE_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class ta_Makefile_gen_class
{
 protected:

 public:
  ta_Makefile_gen_class()
  {
  }
  

  void generate_ta_Makefile(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "CFG_TEE_TA_LOG_LEVEL ?= 4";
    stream << "\n";
    stream << indent_str;
    stream << "CFG_TA_OPTEE_CORE_API_COMPAT_1_1=y";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "# The UUID for the Trusted Application";
    stream << "\n";
    stream << indent_str;
    stream << "BINARY=8aaaf200-2450-11e4-abe2-0002a5d5c51b";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "ifeq ($(wildcard $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk), )";
    stream << "\n";
    stream << indent_str;
    stream << "clean:";
    stream << "\n";
    stream << indent_str;
    stream << "	";
    stream << "@";
    stream << "echo 'Note: $$(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk not found, cannot clean TA'";
    stream << "\n";
    stream << indent_str;
    stream << "	";
    stream << "@";
    stream << "echo 'Note: TA_DEV_KIT_DIR=$(TA_DEV_KIT_DIR)'";
    stream << "\n";
    stream << indent_str;
    stream << "endif";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
  }
};

#endif // TA_MAKEFILE_GEN_CLASS_H
